"""
Generate initial VMEC boundary conditions from target parameters.

Ported from squid_alternative/generate_initial_condition.py.
"""

import os
import numpy as np


def generate_boundary(aspect=10, elongation=6, mirror=0.25, nfp=4, Z2=0.1):
    """
    Compute RBC/ZBS Fourier coefficients for a starting boundary.

    Parameters
    ----------
    aspect : float  — target aspect ratio
    elongation : float  — target elongation
    mirror : float  — target mirror ratio Delta
    nfp : int  — number of field periods
    Z2 : float  — vertical extent of the magnetic axis

    Returns
    -------
    coeffs : dict  — {(n, m): (rbc, zbs)} Fourier coefficients
    """
    b = 1 / np.sqrt(elongation * aspect * aspect)
    a = elongation * b
    cplus = (elongation + 1) * b / 2
    cminus = (elongation - 1) * b / 2
    mirror2 = mirror * 2
    xi = (2 - np.sqrt(4 - mirror2 * mirror2)) / mirror2

    coeffs = {
        (0, 0): (1.5, 0.0),
        (0, 2): (-0.2, Z2),
        (1, 2): (cminus, -cminus),
        (1, 0): (cplus, cplus),
        (1, 1): (-xi * a / 2, -xi * b / 2),
        (-1, 1): (-xi * a / 2, -xi * b / 2),
    }
    return coeffs


def print_boundary(aspect=10, elongation=6, mirror=0.25, nfp=4, Z2=0.1):
    """Print VMEC-format boundary specification to stdout."""
    coeffs = generate_boundary(aspect, elongation, mirror, nfp, Z2)
    print(f'! Boundary shape generated by {os.path.abspath(__file__)}')
    print(f'! Aspect ratio A: {aspect}')
    print(f'! Mirror ratio Delta: {mirror}')
    print(f'! Elongation E: {elongation}')
    print(f'! Vertical extent of the magnetic axis Z0s: {Z2}')
    print(f'NFP = {int(nfp)}')
    for (n, m), (rbc, zbs) in sorted(coeffs.items()):
        print(f'RBC({n:2d},{m:2d}) ={rbc:24.15e},   ZBS({n:2d},{m:2d}) ={zbs:24.15e}')


if __name__ == "__main__":
    print_boundary()
